analysis: 'coordinate'
pdbfile: 'pentapeptide/init-ww-penta.pdb'
dcdform:
    - 'pentapeptide/job**-protein.dcd'
    - '1-25'
pname: 'pentapeptide'
startRes: 0
endRes: 4
icaDim: 8
sliceVal: 1
n_neighbors: 31
affdim: 5
aff_numblock: 10
mult_numblock: 1
n_eigv: 16
saveDir: 'savefiles/'
figDir: 'savefiles/figures'
logfile: 'log.txt'
